"""Generate the client's ONIX traction constants and golden tests from onix_model.py.

Writes common/src/main/java/de/mrjulsen/paw/traction/OnixTractionData.java and
common/src/test/java/de/mrjulsen/paw/traction/OnixTractionTest.java. Tune onix_model.py, audition
with render_onix.py, then run this.
"""
import math, os
from scipy.special import jv
import onix_model as OM

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
JAVA_DATA = os.path.join(REPO, "common/src/main/java/de/mrjulsen/paw/traction/OnixTractionData.java")
JAVA_TEST = os.path.join(REPO, "common/src/test/java/de/mrjulsen/paw/traction/OnixTractionTest.java")


def num(x):
    return "Double.POSITIVE_INFINITY" if x == math.inf else repr(float(x))


def darr(xs):
    return "{" + ", ".join(num(x) for x in xs) + "}"


def iarr(xs):
    return "{" + ", ".join(str(int(x)) for x in xs) + "}"


data = [
    "package de.mrjulsen.paw.traction;",
    "",
    "/** Generated by tools/sound/wmata/build_onix_ingame.py from onix_model.py. Do not edit by hand. */",
    "final class OnixTractionData {",
    "    private OnixTractionData() {}",
    "",
    f"    static final double F1_PER_MPS = {num(OM.F1_PER_MPS)};",
    f"    static final double MPS_PER_BLOCK_PER_TICK = {num(OM.MPS_PER_BLOCK_PER_TICK)};",
    f"    static final double SLIP_HZ = {num(OM.SLIP_HZ)};",
    "",
    f"    static final double[] POWER_LIMITS = {darr(l for l, _ in OM.POWER_SCHEDULE)};",
    f"    static final double[] POWER_CARRIERS = {darr(c for _, c in OM.POWER_SCHEDULE)};",
    f"    static final double[] BRAKE_LIMITS = {darr(l for l, _ in OM.BRAKE_SCHEDULE)};",
    f"    static final double[] BRAKE_CARRIERS = {darr(c for _, c in OM.BRAKE_SCHEDULE)};",
    f"    static final double[] MODULATION_F1 = {darr(f for f, _ in OM.MODULATION)};",
    f"    static final double[] MODULATION_INDEX = {darr(m for _, m in OM.MODULATION)};",
    "",
    f"    static final int[] ELECTRICAL_M = {iarr(m for m, _ in OM.ELECTRICAL_LINES)};",
    f"    static final int[] ELECTRICAL_N = {iarr(n for _, n in OM.ELECTRICAL_LINES)};",
    f"    static final double DIRECT_WEIGHT = {num(OM.DIRECT_WEIGHT)};",
    f"    static final double FORCE_WEIGHT = {num(OM.FORCE_WEIGHT)};",
    f"    static final double RESPONSE_CENTRE_HZ = {num(OM.RESPONSE_CENTRE_HZ)};",
    f"    static final double RESPONSE_WIDTH_HZ = {num(OM.RESPONSE_WIDTH_HZ)};",
    f"    static final double RESPONSE_GAIN_DB = {num(OM.RESPONSE_GAIN_DB)};",
    f"    static final double PWM_LEVEL = {num(OM.PWM_LEVEL)};",
    "",
    f"    static final double ROTOR_ORDER = {num(OM.ROTOR_ORDER)};",
    f"    static final double[] ROTOR_HARMONICS_DB = {darr(OM.ROTOR_HARMONICS_DB)};",
    f"    static final double ROTOR_LEVEL = {num(OM.ROTOR_LEVEL)};",
    f"    static final double ROTOR_COAST = {num(OM.ROTOR_COAST)};",
    f"    static final double ROTOR_ROLLOFF_HZ = {num(OM.ROTOR_ROLLOFF_HZ)};",
    f"    static final double ROTOR_LOW_FADE_FROM_HZ = {num(OM.ROTOR_LOW_FADE_HZ[0])};",
    f"    static final double ROTOR_LOW_FADE_TO_HZ = {num(OM.ROTOR_LOW_FADE_HZ[1])};",
    f"    static final double MAX_LINE_HZ = {num(OM.MAX_LINE_HZ)};",
    "}",
    "",
]
open(JAVA_DATA, "w").write("\n".join(data))

speeds = (0.0, 0.005, 0.02, 0.1, 0.25, 0.33, 0.5, 0.6, 0.65, 0.95, 1.3, 2.0)
demands = ((0.0, 0.0), (1.0, 0.0), (0.4, 0.0), (0.0, 1.0), (0.0, 0.5), (0.2, 0.7), (0.03, 0.0))
cases, freqs, amps = [], [], []
for s in speeds:
    for p, b in demands:
        cases.append((s, p, b))
        for f, a in OM.lines(s, p, b):
            freqs.append(f)
            amps.append(a)
bessel_cases = [(0, 1.0), (1, 2.0), (2, 3.0), (4, 5.0), (5, 4.2), (1, 0.3)]

test = [
    "package de.mrjulsen.paw.traction;",
    "",
    "import static org.junit.jupiter.api.Assertions.assertEquals;",
    "import static org.junit.jupiter.api.Assertions.assertTrue;",
    "",
    "import org.junit.jupiter.api.Test;",
    "",
    "/** Generated by tools/sound/wmata/build_onix_ingame.py: pins the client's line model to onix_model.py. */",
    "class OnixTractionTest {",
    f"    private static final double[] SPEED = {darr(c[0] for c in cases)};",
    f"    private static final double[] POWER = {darr(c[1] for c in cases)};",
    f"    private static final double[] BRAKE = {darr(c[2] for c in cases)};",
    f"    private static final double[] FREQUENCY = {darr(freqs)};",
    f"    private static final double[] AMPLITUDE = {darr(amps)};",
    "",
    "    @Test",
    "    void linesMatchTheModel() {",
    "        double[] frequencies = new double[OnixTraction.LINE_COUNT];",
    "        double[] amplitudes = new double[OnixTraction.LINE_COUNT];",
    "        for (int c = 0; c < SPEED.length; c++) {",
    "            OnixTraction.lines(SPEED[c], POWER[c], BRAKE[c], frequencies, amplitudes);",
    "            for (int i = 0; i < OnixTraction.LINE_COUNT; i++) {",
    "                double f = FREQUENCY[c * OnixTraction.LINE_COUNT + i];",
    "                double a = AMPLITUDE[c * OnixTraction.LINE_COUNT + i];",
    "                String at = \"line \" + i + \" at speed \" + SPEED[c] + \", power \" + POWER[c] + \", brake \" + BRAKE[c];",
    "                assertEquals(f, frequencies[i], 1e-9 * Math.max(1, Math.abs(f)), at);",
    "                assertEquals(a, amplitudes[i], 1e-12 + 1e-9 * Math.abs(a), at);",
    "            }",
    "        }",
    "    }",
    "",
    "    @Test",
    "    void besselMatchesScipy() {",
]
for n, x in bessel_cases:
    test.append(f"        assertEquals({float(jv(n, x))!r}, OnixTraction.bessel({n}, {x!r}), 1e-12);")
test += [
    "    }",
    "",
    "    @Test",
    "    void coastingSilencesTheInverter() {",
    "        double[] frequencies = new double[OnixTraction.LINE_COUNT];",
    "        double[] amplitudes = new double[OnixTraction.LINE_COUNT];",
    "        OnixTraction.lines(0.5, 0, 0, frequencies, amplitudes);",
    "        for (int i = 0; i < OnixTraction.INVERTER_LINE_COUNT; i++) {",
    "            assertEquals(0, amplitudes[i], 0, \"inverter line \" + i);",
    "        }",
    "        double rotor = 0;",
    "        for (int i = OnixTraction.INVERTER_LINE_COUNT; i < OnixTraction.LINE_COUNT; i++) {",
    "            rotor += amplitudes[i];",
    "        }",
    "        assertTrue(rotor > 0, \"the rotor-locked lines stay faintly while coasting\");",
    "    }",
    "",
    "    @Test",
    "    void carrierFollowsTheMeasuredSchedulesWithTheirHysteresis() {",
    "        assertEquals(1235, OnixTraction.carrier(3, false));",
    "        assertEquals(1186, OnixTraction.carrier(20, false));",
    "        assertEquals(1237, OnixTraction.carrier(45, false));",
    "        assertEquals(1455, OnixTraction.carrier(45, true));",
    "        assertEquals(1455, OnixTraction.carrier(50, false));",
    "        assertEquals(1207, OnixTraction.carrier(48, true));",
    "        assertEquals(1230, OnixTraction.carrier(50, true));",
    "        assertEquals(1230, OnixTraction.carrier(70, false));",
    "        assertEquals(1186, OnixTraction.carrier(100, false));",
    "        assertEquals(1186, OnixTraction.carrier(3, true));",
    "    }",
    "}",
    "",
]
open(JAVA_TEST, "w").write("\n".join(test))
print(f"wrote {os.path.relpath(JAVA_DATA, REPO)} and {os.path.relpath(JAVA_TEST, REPO)} ({len(cases)} cases x {OM.LINE_COUNT} lines)")
