package de.mrjulsen.paw.traction;

/** Generated by tools/sound/wmata/build_onix_ingame.py from onix_model.py. Do not edit by hand. */
final class OnixTractionData {
    private OnixTractionData() {}

    static final double F1_PER_MPS = 4.5;
    static final double MPS_PER_BLOCK_PER_TICK = 20.0;
    static final double SLIP_HZ = 3.0;

    static final double[] POWER_LIMITS = {6.0, 29.3, 35.2, 46.9, 52.7, 55.7, 85.0, Double.POSITIVE_INFINITY};
    static final double[] POWER_CARRIERS = {1235.0, 1186.0, 1207.0, 1237.0, 1455.0, 1207.0, 1230.0, 1186.0};
    static final double[] BRAKE_LIMITS = {23.4, 32.2, 41.0, 46.9, 49.8, 82.0, Double.POSITIVE_INFINITY};
    static final double[] BRAKE_CARRIERS = {1186.0, 1207.0, 1237.0, 1455.0, 1207.0, 1230.0, 1186.0};
    static final double[] MODULATION_F1 = {0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0, 110.0};
    static final double[] MODULATION_INDEX = {0.5, 0.57, 0.7, 0.72, 0.78, 0.83, 0.87, 0.97, 1.01, 1.05, 1.07, 1.08};

    static final int[] ELECTRICAL_M = {1, 1, 1, 1, 2, 2, 3, 3};
    static final int[] ELECTRICAL_N = {-4, -2, 2, 4, -1, 1, -2, 2};
    static final double DIRECT_WEIGHT = 0.5;
    static final double FORCE_WEIGHT = 1.0;
    static final double RESPONSE_CENTRE_HZ = 2450.0;
    static final double RESPONSE_WIDTH_HZ = 350.0;
    static final double RESPONSE_GAIN_DB = 16.0;
    static final double PWM_LEVEL = 0.05;

    static final double ROTOR_ORDER = 11.7;
    static final double[] ROTOR_HARMONICS_DB = {-12.0, 0.0, -14.0};
    static final double ROTOR_LEVEL = 0.035;
    static final double ROTOR_COAST = 0.12;
    static final double ROTOR_ROLLOFF_HZ = 1500.0;
    static final double ROTOR_LOW_FADE_FROM_HZ = 150.0;
    static final double ROTOR_LOW_FADE_TO_HZ = 350.0;
    static final double MAX_LINE_HZ = 5000.0;
}
