package de.mrjulsen.paw.traction;

/**
 * Generated by tools/sound/wmata/build_wmata_ingame.py. Do not edit by hand; change the
 * tuning there and regenerate. Frequencies are the brief's measured features; level knots,
 * gains and scales were tuned offline against the reference recording.
 */
public final class WmataTractionData {
    private WmataTractionData() {}

    /** Length of the reference departure the curves describe, in seconds. */
    public static final double TIMELINE_SECONDS = 10.0;

    public static final double UPPER_REFERENCE_HZ = 2440.0;
    public static final double LOW_REFERENCE_HZ = 700.0;
    public static final double BRIEF_REFERENCE_HZ = 2890.0;
    public static final double MID_REFERENCE_HZ = 1350.0;

    static final double[][] UPPER_FREQUENCY_KNOTS = {{0.0, 2495.0}, {0.7, 2495.0}, {1.0, 2380.0}, {3.0, 2380.0}, {4.0, 2420.0}, {5.0, 2575.0}, {5.75, 2590.0}, {7.0, 2490.0}, {8.0, 2575.0}, {10.0, 2520.0}};
    static final double[][] LOW_FREQUENCY_KNOTS = {{3.0, 556.0}, {3.25, 590.0}, {3.5, 630.0}, {3.75, 666.0}, {4.0, 699.0}, {4.25, 739.0}, {4.75, 810.0}, {5.0, 843.0}};
    static final double[][] BRIEF_FREQUENCY_KNOTS = {{6.0, 2940.0}, {6.25, 2941.0}, {6.5, 2877.0}, {6.75, 2845.0}, {7.0, 2845.0}};
    static final double[][] MID_FREQUENCY_KNOTS = {{7.75, 1282.0}, {8.0, 1334.0}, {8.25, 1346.0}, {8.5, 1368.0}, {8.75, 1433.0}};
    static final double[][] UPPER_LEVEL_KNOTS_DB = {{0.0, -8.913883208425624}, {0.25, -8.913883208425624}, {0.75, -7.907177920339251}, {1.25, -6.260565922813122}, {1.75, -4.348382990649057}, {2.25, -3.295015872355492}, {2.75, -2.327233174750077}, {3.25, -2.2731123283891748}, {3.75, -1.7790741215794341}, {4.25, -2.5482422308526367}, {4.75, -2.3954215783077686}, {5.25, -2.304326545643754}, {5.75, -0.8640561810754548}, {6.25, 0.0}, {6.75, -0.2316008999158825}, {7.25, -0.8087639227433101}, {7.75, -1.4772752783206329}, {8.25, -1.4845261301099413}, {8.75, -2.22340854075442}, {9.25, -2.958087595502967}, {9.75, -3.2704576385907416}, {10.0, -3.2704576385907416}};
    static final double[][] UPPER_LINE_CUT_KNOTS_DB = {{0.0, 0.0}, {2.5, 0.0}, {4.0, -8.0}, {10.0, -8.0}};
    static final double[][] UPPER_DIFFUSE_LEVEL_KNOTS_DB = {{0.0, -60.0}, {2.5, -60.0}, {4.0, 0.0}, {10.0, 0.0}};
    static final double[][] LOW_LEVEL_KNOTS_DB = {{0.0, -60.0}, {2.8, -60.0}, {3.0, -9.0}, {3.5, 0.0}, {4.0, 3.0}, {4.5, 0.0}, {5.0, -2.0}, {5.3, -21.0}, {5.5, -60.0}, {10.0, -60.0}};
    static final double[][] BRIEF_LEVEL_KNOTS_DB = {{0.0, -60.0}, {6.0, -60.0}, {6.2, -8.0}, {6.5, -8.0}, {6.8, -14.0}, {7.0, -60.0}, {10.0, -60.0}};
    static final double[][] MID_LEVEL_KNOTS_DB = {{0.0, -60.0}, {7.5, -60.0}, {7.75, -15.0}, {8.25, -9.0}, {8.5, -9.0}, {8.75, -12.0}, {9.0, -24.0}, {9.2, -60.0}, {10.0, -60.0}};
    static final double[][] NOISE_LEVEL_KNOTS_DB = {{0.0, -6.691210614591498}, {0.25, -6.691210614591498}, {0.75, -6.383775337846934}, {1.25, -5.870851785698932}, {1.75, -5.143627089740114}, {2.25, -4.637769604886039}, {2.75, -3.7281427938472262}, {3.25, -2.8016856613015264}, {3.75, -1.9118275663821152}, {4.25, -1.0673813774963747}, {4.75, -0.7642303235496115}, {5.25, -0.7365192340117375}, {5.75, -0.9869725025132396}, {6.25, -0.9644404340151169}, {6.75, -1.2393651971973298}, {7.25, -1.1536216982113388}, {7.75, -0.8399288619411891}, {8.25, -0.40418252889662654}, {8.75, -0.3590792935310816}, {9.25, -0.18540846426236612}, {9.75, 0.0}, {10.0, 0.0}};

    static final double LOW_GAIN_DB = 0.0;
    static final double BRIEF_GAIN_DB = -8.0;
    static final double MID_GAIN_DB = 6.0;

    static final double TONAL_VOICE_SCALE = 0.40336190108133346;
    static final double NOISE_VOICE_SCALE = 0.999;
}
