package de.mrjulsen.paw.traction;

/**
 * Generated by tools/sound/wmata/build_wmata_ingame.py. Do not edit by hand; change the
 * tuning there and regenerate. Frequencies are the brief's measured features; level knots,
 * gains and scales were tuned offline against the reference recording, except the noise bed,
 * which has the platform background removed and a level chosen by ear.
 */
public final class WmataTractionData {
    private WmataTractionData() {}

    /** Length of the reference departure the curves describe, in seconds. */
    public static final double TIMELINE_SECONDS = 10.0;

    public static final double UPPER_REFERENCE_HZ = 2440.0;
    public static final double RIDGE_REFERENCE_HZ = 850.0;
    public static final double BRIEF_REFERENCE_HZ = 2890.0;

    static final double[][] UPPER_FREQUENCY_KNOTS = {{0.0, 2495.0}, {0.7, 2495.0}, {1.0, 2380.0}, {3.0, 2380.0}, {4.0, 2420.0}, {5.0, 2575.0}, {5.75, 2590.0}, {7.0, 2490.0}, {8.0, 2575.0}, {10.0, 2520.0}};
    static final double[][] RIDGE_FREQUENCY_KNOTS = {{2.25, 435.34999999999997}, {2.5, 473.5}, {3.0, 556.0}, {3.25, 590.0}, {3.5, 630.0}, {3.75, 666.0}, {4.0, 699.0}, {4.25, 739.0}, {4.75, 810.0}, {5.0, 843.0}, {5.5, 931.3}, {6.0, 1007.5999999999999}, {6.5, 1083.9}, {7.0, 1160.2}, {7.5, 1236.5}, {7.75, 1282.0}, {8.0, 1334.0}, {8.25, 1346.0}, {8.5, 1368.0}, {8.75, 1433.0}, {9.25, 1503.55}, {9.75, 1579.85}, {10.0, 1618.0}};
    static final double[][] BRIEF_FREQUENCY_KNOTS = {{6.0, 2940.0}, {6.25, 2941.0}, {6.5, 2877.0}, {6.75, 2845.0}, {7.0, 2845.0}};
    static final double[][] UPPER_LEVEL_KNOTS_DB = {{0.0, -8.913883208425624}, {0.25, -8.913883208425624}, {0.75, -7.907177920339251}, {1.25, -6.260565922813122}, {1.75, -4.348382990649057}, {2.25, -3.295015872355492}, {2.75, -2.327233174750077}, {3.25, -2.2731123283891748}, {3.75, -1.7790741215794341}, {4.25, -2.5482422308526367}, {4.75, -2.3954215783077686}, {5.25, -2.304326545643754}, {5.75, -0.8640561810754548}, {6.25, 0.0}, {6.75, -0.2316008999158825}, {7.25, -0.8087639227433101}, {7.75, -1.4772752783206329}, {8.25, -1.4845261301099413}, {8.75, -2.22340854075442}, {9.25, -2.958087595502967}, {9.75, -3.2704576385907416}, {10.0, -3.2704576385907416}};
    static final double[][] UPPER_LINE_CUT_KNOTS_DB = {{0.0, 0.0}, {2.5, 0.0}, {4.0, -8.0}, {10.0, -8.0}};
    static final double[][] UPPER_DIFFUSE_LEVEL_KNOTS_DB = {{0.0, -60.0}, {2.5, -60.0}, {4.0, 0.0}, {10.0, 0.0}};
    static final double[][] RIDGE_LEVEL_KNOTS_DB = {{0.0, -60.0}, {2.0, -60.0}, {2.5, -12.0}, {3.0, -9.0}, {3.5, 0.0}, {4.0, 3.0}, {4.5, 0.0}, {5.0, -2.0}, {5.5, -6.0}, {6.0, -8.0}, {6.5, -8.5}, {7.0, -8.0}, {7.5, -7.0}, {8.0, -4.0}, {8.25, -3.0}, {8.5, -3.0}, {8.75, -6.0}, {9.25, -10.0}, {9.75, -11.0}, {10.0, -11.0}};
    static final double[][] BRIEF_LEVEL_KNOTS_DB = {{0.0, -60.0}, {6.0, -60.0}, {6.2, -8.0}, {6.5, -8.0}, {6.8, -14.0}, {7.0, -60.0}, {10.0, -60.0}};
    static final double[][] NOISE_LEVEL_KNOTS_DB = {{0.0, -10.315163987532666}, {0.25, -10.315163987532666}, {0.75, -9.541315271813904}, {1.25, -8.403931586938203}, {1.75, -7.014507714830708}, {2.25, -6.153144638013239}, {2.75, -4.7504413592189385}, {3.25, -3.4557376108605213}, {3.75, -2.2991519931401436}, {4.25, -1.2581900510127582}, {4.75, -0.8950985962026408}, {5.25, -0.8621535716158661}, {5.75, -1.1613903681197122}, {6.25, -1.1343303772140751}, {6.75, -1.4664866883039707}, {7.25, -1.362421532126355}, {7.75, -0.9852990069646042}, {8.25, -0.47003059680502446}, {8.75, -0.4172203935642982}, {9.25, -0.21473155189382565}, {9.75, 0.0}, {10.0, 0.0}};

    static final double RIDGE_GAIN_DB = -8.0;
    static final double BRIEF_GAIN_DB = -16.0;

    static final double TONAL_VOICE_SCALE = 0.999;
    static final double NOISE_VOICE_SCALE = 0.5410191384420775;
}
