package de.mrjulsen.paw.traction;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

/**
 * Generated by tools/sound/wmata/build_wmata_ingame.py. The expected values come from
 * SciPy's PchipInterpolator on the same knots, so this pins the Java curves to the offline
 * synthesis the profile was tuned with.
 */
class WmataTractionTest {
    private static final double[] TIMES = {-1.0, 0.0, 0.13, 0.5, 0.7, 0.85, 1.0, 1.7, 2.5, 2.8, 2.9, 3.0, 3.1, 3.33, 3.8, 4.1, 4.5, 4.9, 5.25, 5.4, 5.6, 6.1, 6.33, 6.9, 7.3, 7.6, 7.8, 8.1, 8.6, 8.9, 9.1, 9.5, 10.0, 12.0};
    private static final double[] UPPERFREQUENCY = {2495.0, 2495.0, 2495.0, 2495.0, 2495.0, 2437.5, 2380.0, 2380.0, 2380.0, 2380.0, 2380.0, 2380.0, 2380.547692307692, 2385.5533415384616, 2407.700512820513, 2429.183210175651, 2501.177064405411, 2568.4642761962446, 2582.6859142607173, 2586.225756780402, 2589.260157480315, 2570.8704, 2545.3906688, 2491.8176000000003, 2508.3599999999997, 2545.08, 2566.16, 2574.993125, 2573.515, 2569.988125, 2565.849375, 2551.796875, 2520.0, 2520.0};
    private static final double[] LOWFREQUENCY = {556.0, 556.0, 556.0, 556.0, 556.0, 556.0, 556.0, 556.0, 556.0, 556.0, 556.0, 556.0, 568.9033513513513, 602.4666974679943, 672.6823918999404, 714.6524712328766, 775.4501077005924, 830.0223586429727, 843.0, 843.0, 843.0, 843.0, 843.0, 843.0, 843.0, 843.0, 843.0, 843.0, 843.0, 843.0, 843.0, 843.0, 843.0, 843.0};
    private static final double[] BRIEFFREQUENCY = {2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.0, 2940.7839999999997, 2928.5044693333334, 2845.0, 2845.0, 2845.0, 2845.0, 2845.0, 2845.0, 2845.0, 2845.0, 2845.0, 2845.0, 2845.0};
    private static final double[] MIDFREQUENCY = {1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1282.0, 1296.0, 1339.5411764705882, 1387.309793103448, 1433.0, 1433.0, 1433.0, 1433.0, 1433.0};
    private static final double[] UPPERLINEVOLUME = {0.1445442149730726, 0.1445442149730726, 0.1445442149730726, 0.15043850357908628, 0.1599065075208355, 0.16751895159838073, 0.17711335839255937, 0.24037723766607955, 0.29566691855754457, 0.28065982363086034, 0.2631485026558134, 0.24378865909159056, 0.224006504829274, 0.18298102144122536, 0.13649016878282186, 0.12206461319411618, 0.12061181616873053, 0.1222381724507716, 0.1231625147827014, 0.1270253877674528, 0.1378916678017693, 0.15840374544025454, 0.16041900077673243, 0.15395835379892867, 0.14515041884351432, 0.13715293042890483, 0.13544697829257518, 0.13539643808811022, 0.1281959886753447, 0.12093595851440615, 0.1165805575121878, 0.11149143370808774, 0.1101975637617924, 0.1101975637617924};
    private static final double[] UPPERDIFFUSEVOLUME = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0006335490557273937, 0.0010389295246260725, 0.0018556453603910882, 0.003524200673159093, 0.017114903801003053, 0.23436165488010824, 0.30661244564976575, 0.30296318451396204, 0.3070484067916214, 0.30937024975326577, 0.31907334799030773, 0.3463682093694908, 0.3978922188716729, 0.402954311407399, 0.3867258999250804, 0.36460136762095613, 0.3445125849861435, 0.3402274269620923, 0.340100475708251, 0.3220137645275542, 0.3037773932739423, 0.2928371205926868, 0.2800538195608955, 0.2768037651986582, 0.2768037651986582};
    private static final double[] LOWVOLUME = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.006803165000395257, 0.14311820321036614, 0.20803364805698518, 0.3348918847072246, 0.5302673352930295, 0.5545425500847262, 0.40336190108133346, 0.34533644075842235, 0.062384784162710594, 0.002864012628687925, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
    private static final double[] BRIEFVOLUME = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0032040174684095923, 0.06392855311219785, 0.0020275242705299805, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
    private static final double[] MIDVOLUME = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.004653579985007522, 0.16389439670714126, 0.2692456660594163, 0.2666458784703908, 0.10796058614206297, 0.005115429765420154, 0.0, 0.0, 0.0};
    private static final double[] NOISEVOLUME = {0.46238629953525123, 0.46238629953525123, 0.46238629953525123, 0.4680454931888868, 0.4768582667704692, 0.48366189023893946, 0.4918615148685069, 0.5485550325084655, 0.6148141606591109, 0.6573015268490879, 0.6715086202561361, 0.6860936133048477, 0.7009625393259936, 0.7357433378991005, 0.8099629055837358, 0.8640262260102448, 0.9041618865945514, 0.9162763714617396, 0.9177819803127768, 0.912083567225444, 0.8972671301394871, 0.8935114458730573, 0.8920729376764442, 0.8671595886561795, 0.8764050214897923, 0.8952086114194138, 0.9112124959499651, 0.9444925436489912, 0.9568758160908671, 0.9626059691644203, 0.9712404972135952, 0.9909487642206176, 0.999, 0.999};

    @Test
    void curvesMatchOfflineSynthesis() {
        for (int i = 0; i < TIMES.length; i++) {
            double t = TIMES[i];
            assertEquals(UPPERFREQUENCY[i], WmataTraction.upperFrequency(t), 1e-9, "upperFrequency at t=" + t);
            assertEquals(LOWFREQUENCY[i], WmataTraction.lowFrequency(t), 1e-9, "lowFrequency at t=" + t);
            assertEquals(BRIEFFREQUENCY[i], WmataTraction.briefFrequency(t), 1e-9, "briefFrequency at t=" + t);
            assertEquals(MIDFREQUENCY[i], WmataTraction.midFrequency(t), 1e-9, "midFrequency at t=" + t);
            assertEquals(UPPERLINEVOLUME[i], WmataTraction.upperLineVolume(t), 1e-9, "upperLineVolume at t=" + t);
            assertEquals(UPPERDIFFUSEVOLUME[i], WmataTraction.upperDiffuseVolume(t), 1e-9, "upperDiffuseVolume at t=" + t);
            assertEquals(LOWVOLUME[i], WmataTraction.lowVolume(t), 1e-9, "lowVolume at t=" + t);
            assertEquals(BRIEFVOLUME[i], WmataTraction.briefVolume(t), 1e-9, "briefVolume at t=" + t);
            assertEquals(MIDVOLUME[i], WmataTraction.midVolume(t), 1e-9, "midVolume at t=" + t);
            assertEquals(NOISEVOLUME[i], WmataTraction.noiseVolume(t), 1e-9, "noiseVolume at t=" + t);
        }
    }

    @Test
    void volumesStayWithinWhatTheEngineCanPlay() {
        for (double t = 0; t <= WmataTractionData.TIMELINE_SECONDS; t += 0.005) {
            double upperLineVolume = WmataTraction.upperLineVolume(t);
            assertTrue(upperLineVolume >= 0 && upperLineVolume <= 1.0 + 1e-12, "upperLineVolume at t=" + t + " was " + upperLineVolume);
            double upperDiffuseVolume = WmataTraction.upperDiffuseVolume(t);
            assertTrue(upperDiffuseVolume >= 0 && upperDiffuseVolume <= 1.0 + 1e-12, "upperDiffuseVolume at t=" + t + " was " + upperDiffuseVolume);
            double lowVolume = WmataTraction.lowVolume(t);
            assertTrue(lowVolume >= 0 && lowVolume <= 1.0 + 1e-12, "lowVolume at t=" + t + " was " + lowVolume);
            double briefVolume = WmataTraction.briefVolume(t);
            assertTrue(briefVolume >= 0 && briefVolume <= 1.0 + 1e-12, "briefVolume at t=" + t + " was " + briefVolume);
            double midVolume = WmataTraction.midVolume(t);
            assertTrue(midVolume >= 0 && midVolume <= 1.0 + 1e-12, "midVolume at t=" + t + " was " + midVolume);
            double noiseVolume = WmataTraction.noiseVolume(t);
            assertTrue(noiseVolume >= 0 && noiseVolume <= 1.0 + 1e-12, "noiseVolume at t=" + t + " was " + noiseVolume);
        }
    }

    @Test
    void pitchRatiosStayInsideTheEngineClamp() {
        for (double t = 0; t <= WmataTractionData.TIMELINE_SECONDS; t += 0.005) {
            double upperFrequencyRatio = WmataTraction.upperFrequency(t) / WmataTractionData.UPPER_REFERENCE_HZ;
            assertTrue(upperFrequencyRatio >= 0.5 && upperFrequencyRatio <= 2.0, "upperFrequency ratio at t=" + t);
            double lowFrequencyRatio = WmataTraction.lowFrequency(t) / WmataTractionData.LOW_REFERENCE_HZ;
            assertTrue(lowFrequencyRatio >= 0.5 && lowFrequencyRatio <= 2.0, "lowFrequency ratio at t=" + t);
            double briefFrequencyRatio = WmataTraction.briefFrequency(t) / WmataTractionData.BRIEF_REFERENCE_HZ;
            assertTrue(briefFrequencyRatio >= 0.5 && briefFrequencyRatio <= 2.0, "briefFrequency ratio at t=" + t);
            double midFrequencyRatio = WmataTraction.midFrequency(t) / WmataTractionData.MID_REFERENCE_HZ;
            assertTrue(midFrequencyRatio >= 0.5 && midFrequencyRatio <= 2.0, "midFrequency ratio at t=" + t);
        }
    }
}
